
import { Project } from '../types';

export interface LocalizedProject extends Omit<Project, 'description'> {
  description: {
    en: string;
    de: string;
    fr: string;
  };
  longDescription: {
    en: string;
    de: string;
    fr: string;
  };
  image?: string;
}

export const projects: LocalizedProject[] = [
  {
    title: "Green Hydrogen Project",
    description: {
      en: "Mechanical engineering group project focused on Electrolysis efficiency, Hydrogen embrittlement prevention, and storage pressure calculations.",
      de: "Gruppenprojekt im Maschinenbau mit Fokus auf Elektrolyse-Effizienz, Vermeidung von Wasserstoffversprödung und Speicherdruckberechnungen.",
      fr: "Projet de groupe en génie mécanique axé sur l'efficacité de l'électrolyse, la prévention de la fragilisation par l'hydrogène et les calculs de pression de stockage."
    },
    longDescription: {
      en: "This project addresses the challenge of renewable energy intermittency by exploring green hydrogen as a storage solution. The core task is to build a crane from aluminum profiles, powered by a fuel cell that uses hydrogen produced via electrolysis. The energy for the electrolysis is generated by a solar cell. The project's main goal is to achieve the highest possible potential energy, by lifting a weight, demonstrating the entire energy conversion chain from solar energy to mechanical work. The educational objectives include understanding the fundamentals of electrical engineering, the functionality of solar cells, electrolyzers, and fuel cells, and explaining the measured results.",
      de: "Dieses Projekt befasst sich mit der Herausforderung der Intermittenz erneuerbarer Energien durch die Erforschung von grünem Wasserstoff als Speicherlösung. Die Kernaufgabe besteht darin, einen Kran aus Aluminiumprofilen zu bauen, der von einer Brennstoffzelle angetrieben wird, die Wasserstoff aus der Elektrolyse verwendet. Die Energie für die Elektrolyse wird von einer Solarzelle erzeugt. Das Hauptziel des Projekts ist es, die höchstmögliche potenzielle Energie durch das Heben eines Gewichts zu erreichen und so die gesamte Energieumwandlungskette von Sonnenenergie zu mechanischer Arbeit zu demonstrieren. Die Bildungsziele umfassen das Verständnis der Grundlagen der Elektrotechnik, der Funktionsweise von Solarzellen, Elektrolyseuren und Brennstoffzellen sowie die Erläuterung der Messergebnisse.",
      fr: "Ce projet aborde le défi de l'intermittence des énergies renouvelables en explorant l'hydrogène vert comme solution de stockage. La tâche principale consiste à construire une grue à partir de profilés en aluminium, alimentée par une pile à combustible qui utilise de l'hydrogène produit par électrolyse. L'énergie pour l'électrolyse est générée par une cellule solaire. L'objectif principal du projet est d'atteindre l'énergie potentielle la plus élevée possible, en soulevant un poids, démontrant ainsi toute la chaîne de conversion d'énergie, de l'énergie solaire au travail mécanique. Les objectifs pédagogiques comprennent la compréhension des principes fondamentaux de l'électrotechnique, du fonctionnement des cellules solaires, des électrolyseurs et des piles à combustible, ainsi que l'explication des résultats mesurés."
    },
    image: "/images/green-hydrogen.jpg",
    tech: ["Photovoltaics", "Electrolysis", "PEM Fuel Cell", "Energy Storage"],
  },
  {
    title: "Home Lab",
    description: {
      en: "A personal portfolio hosted on a home server, featuring an automated CI/CD pipeline using GitHub Actions and self-hosted runners.",
      de: "Ein persönliches Portfolio, das auf einem Heimserver gehostet wird, mit einer automatisierten CI/CD-Pipeline unter Verwendung von GitHub Actions und selbstgehosteten Runnern.",
      fr: "Un portfolio personnel hébergé sur un serveur domestique, doté d'un pipeline CI/CD automatisé utilisant GitHub Actions et des runners auto-hébergés."
    },
    longDescription: {
      en: "This project is the infrastructure that powers this website. I configured a Linux server from scratch, set up Nginx as a reverse proxy, and implemented a complete CI/CD pipeline with GitHub Actions. When I push a change to the GitHub repository, a self-hosted runner on my server automatically pulls the changes, builds the site, and deploys it. This project demonstrates my ability to manage a full-stack system and my commitment to automated, repeatable processes.",
      de: "Dieses Projekt ist die Infrastruktur, die diese Website antreibt. Ich habe einen Linux-Server von Grund auf neu konfiguriert, Nginx als Reverse-Proxy eingerichtet und eine vollständige CI/CD-Pipeline mit GitHub Actions implementiert. Wenn ich eine Änderung in das GitHub-Repository pushe, zieht ein selbst gehosteter Runner auf meinem Server automatisch die Änderungen, erstellt die Website und stellt sie bereit. Dieses Projekt demonstriert meine Fähigkeit, ein Full-Stack-System zu verwalten, und mein Engagement für automatisierte, wiederholbare Prozesse.",
      fr: "Ce projet est l'infrastructure qui alimente ce site Web. J'ai configuré un serveur Linux à partir de zéro, configuré Nginx en tant que proxy inverse et mis en œuvre un pipeline CI/CD complet avec GitHub Actions. Lorsque je pousse une modification dans le référentiel GitHub, un exécuteur auto-hébergé sur mon serveur extrait automatiquement les modifications, construit le site et le déploie. Ce projet démontre ma capacité à gérer un système full-stack et mon engagement envers des processus automatisés et reproductibles."
    },
    image: "/images/home-lab.jpg",
    tech: ["Astro", "Nginx", "Linux", "GitHub Actions", "CI/CD"],
    link: "https://github.com/Vansh1516/projectX",
  },
  {
    title: "BotBro: Sarcastic AI Agent",
    description: {
      en: "An intelligent Telegram bot designed to manage the daily friction of shared flat (WG) living. Unlike simple script bots, BotBro utilizes a ReAct (Reason + Act) agent architecture to autonomously use tools, managing cleaning schedules, setting reminders, and performing web searches—all while maintaining a sarcastic, German-infused persona.",
      de: "Ein intelligenter Telegram-Bot, der entwickelt wurde, um die täglichen Reibungen des WG-Lebens zu bewältigen. Im Gegensatz zu einfachen Skript-Bots verwendet BotBro eine ReAct (Reason + Act) Agentenarchitektur, um autonom Werkzeuge zu verwenden, Reinigungspläne zu verwalten, Erinnerungen zu setzen und Websuchen durchzuführen – alles unter Beibehaltung einer sarkastischen, deutsch geprägten Persönlichkeit.",
      fr: "Un bot Telegram intelligent conçu pour gérer les frictions quotidiennes de la vie en colocation (WG). Contrairement aux simples bots de script, BotBro utilise une architecture d'agent ReAct (Raisonner + Agir) pour utiliser de manière autonome des outils, gérer les plannings de nettoyage, définir des rappels et effectuer des recherches sur le Web, le tout en conservant une personnalité sarcastique et imprégnée d'allemand."
    },
    longDescription: {
      en: "BotBro is a personal project that combines my interest in automation and AI. I used Python and the Groq API to build a conversational agent that can understand natural language and perform tasks. The ReAct architecture allows the bot to reason about a user's request, decide which tool to use (e.g., a web search or a database lookup), and then respond intelligently. This project was a great way to learn about the practical application of AI and the challenges of building a robust, asynchronous system.",
      de: "BotBro ist ein persönliches Projekt, das mein Interesse an Automatisierung und KI verbindet. Ich habe Python und die Groq-API verwendet, um einen Konversationsagenten zu erstellen, der natürliche Sprache verstehen und Aufgaben ausführen kann. Die ReAct-Architektur ermöglicht es dem Bot, über die Anfrage eines Benutzers nachzudenken, zu entscheiden, welches Werkzeug er verwenden soll (z. B. eine Websuche oder eine Datenbankabfrage), und dann intelligent zu antworten. Dieses Projekt war eine großartige Möglichkeit, die praktische Anwendung von KI und die Herausforderungen beim Aufbau eines robusten, asynchronen Systems kennenzulernen.",
      fr: "BotBro est un projet personnel qui combine mon intérêt pour l'automatisation et l'IA. J'ai utilisé Python et l'API Groq pour créer un agent conversationnel capable de comprendre le langage naturel et d'effectuer des tâches. L'architecture ReAct permet au bot de raisonner sur la demande d'un utilisateur, de décider quel outil utiliser (par exemple, une recherche sur le Web ou une recherche dans une base de données), puis de répondre intelligemment. Ce projet a été un excellent moyen d'en apprendre davantage sur l'application pratique de l'IA et les défis de la création d'un système asynchrone robuste."
    },
    image: "/images/botbro.jpg",
    tech: ["Python", "Groq API", "AsyncIO", "ReAct Architecture"],
    link: "https://github.com/Vansh1516/Stefan_Chatbot/tree/main",
  },
  {
    title: "Independent Wind Tunnel Fabrication",
    description: {
      en: "An independent engineering side project to design, construct, and validate a Modular Low-Speed Wind Tunnel (MLWT) for aerodynamic testing.",
      de: "Ein unabhängiges Ingenieur-Nebenprojekt zur Konstruktion, zum Bau und zur Validierung eines modularen Niedriggeschwindigkeits-Windkanals (MLWT) für aerodynamische Tests.",
      fr: "Un projet d'ingénierie parallèle indépendant pour concevoir, construire et valider une soufflerie modulaire à basse vitesse (MLWT) pour les essais aérodynamiques."
    },
    longDescription: {
      en: "This independent project aims to design, construct, and validate a Modular Low-Speed Wind Tunnel (MLWT) that produces laminar flow for aerodynamic testing. The project requires proficiency in CAD (Fusion 360), precision assembly, and the practical application of fundamental fluid dynamics principles, such as the Continuity Equation, Bernoulli's Principle, and the Reynolds Number. The fabrication process focuses on precision, using a 120mm PWM fan, a custom honeycomb straightener, and 3mm acrylic for the test section. Upon completion, the tunnel will undergo rigorous calibration, including velocity mapping, flow visualization, and lift/drag observation.",
      de: "Dieses unabhängige Projekt zielt darauf ab, einen modularen Niedriggeschwindigkeits-Windkanal (MLWT) zu entwerfen, zu bauen und zu validieren, der eine laminare Strömung für aerodynamische Tests erzeugt. Das Projekt erfordert Kenntnisse in CAD (Fusion 360), Präzisionsmontage und die praktische Anwendung grundlegender Prinzipien der Fluiddynamik wie der Kontinuitätsgleichung, dem Bernoulli-Prinzip und der Reynolds-Zahl. Der Herstellungsprozess konzentriert sich auf Präzision und verwendet einen 120-mm-PWM-Lüfter, einen benutzerdefinierten Waben-Gleichrichter und 3-mm-Acryl für den Testabschnitt. Nach Fertigstellung wird der Tunnel einer strengen Kalibrierung unterzogen, einschließlich Geschwindigkeitskartierung, Strömungsvisualisierung und Auftriebs-/Widerstandsbeobachtung.",
      fr: "Ce projet indépendant vise à concevoir, construire et valider une soufflerie modulaire à basse vitesse (MLWT) qui produit un écoulement laminaire pour les essais aérodynamiques. Le projet nécessite une maîtrise de la CAO (Fusion 360), un assemblage de précision et l'application pratique des principes fondamentaux de la dynamique des fluides, tels que l'équation de continuité, le principe de Bernoulli et le nombre de Reynolds. Le processus de fabrication est axé sur la précision, en utilisant un ventilateur PWM de 120 mm, un redresseur en nid d'abeille personnalisé et de l'acrylique de 3 mm pour la section de test. Une fois terminé, le tunnel subira un étalonnage rigoureux, comprenant une cartographie de la vitesse, une visualisation de l'écoulement et une observation de la portance/traînée."
    },
    image: "/images/wind-tunnel.jpg",
    tech: ["CAD", "Fusion 360", "Fluid Dynamics", "Aerodynamics", "Fabrication"],
  },
];
